sudo: false
language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
env:
  global:
    - PAYPAL_CLIENT_ID=paypal_client_id
    - PAYPAL_CLIENT_SECRET=paypal_client_secret
before_install: gem install bundler -v 1.16.1
matrix:
  fast_finish: true
  allow_failures:
  - rvm: 2.6.0
script:
  - bundle exec rspec 

jobs:
  include:
    - stage: integration
      name: Run integration against paypal
      rvm: 2.5.3
      script:
        - bundle exec rspec spec/integration_spec.rb
