sudo: false
language: ruby
rvm:
- 2.4.9
- 2.5.6
- 2.6.5
- 2.7.0
env:
- ACTIVESUPPORT_VERSION='> 5'
- ACTIVESUPPORT_VERSION=4.2.11

before_install: gem install bundler
matrix:
  fast_finish: true
script:
- bundle exec rspec --exclude-pattern "spec/integration/*"
jobs:
  include:
  - stage: integration
    name: Run integration against paypal
    rvm: 2.5.3
    allow_failure: true
    script:
    - bundle exec rspec spec/integration/
